name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: echo "hello"

